In [1]:
import pandas as pd

In [7]:
Revenue_Growth_Factor = 0.18 
EBITDA_Margin = 0.45 
Taxes= 0.21 
Capital_Expenditures= 0.03 
Working_Capital_Increase= 0.06
EBITDA_Exit_Multiple= 32.70
Discount_Factor= 0.94

In [9]:
dates = pd.date_range(start='2022', end='2032',freq='Y')
dates

DatetimeIndex(['2022-12-31', '2023-12-31', '2024-12-31', '2025-12-31',
               '2026-12-31', '2027-12-31', '2028-12-31', '2029-12-31',
               '2030-12-31', '2031-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [20]:
df=pd.DataFrame(index=dates)
df.loc['2022-12-31',"Revenue"]=222*(1+ Revenue_Growth_Factor) 
df

            Revenue
2022-12-31   261.96
2023-12-31      NaN
2024-12-31      NaN
2025-12-31      NaN
2026-12-31      NaN
2027-12-31      NaN
2028-12-31      NaN
2029-12-31      NaN
2030-12-31      NaN
2031-12-31      NaN

In [22]:
for i in range (1,len(df)):
    df.iloc[i]["Revenue"]=df.iloc[i-1]["Revenue"]*(1+Revenue_Growth_Factor)
df

                Revenue
2022-12-31   261.960000
2023-12-31   309.112800
2024-12-31   364.753104
2025-12-31   430.408663
2026-12-31   507.882222
2027-12-31   599.301022
2028-12-31   707.175206
2029-12-31   834.466743
2030-12-31   984.670757
2031-12-31  1161.911493

In [29]:
df['EBITDA']=df["Revenue"]*EBITDA_Margin
df['Taxes']= -df['EBITDA']*Taxes
df['Capital Expenditures']= -df["Revenue"]*Capital_Expenditures
df['Working Capital Increase']=-df["Revenue"]*Working_Capital_Increase
df["Cash Flow"] = df.drop(columns="Revenue").sum(axis=1)
df["Discount Factor"] = Discount_Factor
df["Discount Factor"] = df["Discount Factor"].cumprod()
df["Present Value Free Cash Flow"] = df["Cash Flow"] * df["Discount Factor"]
df

,Revenue,EBITDA,Taxes,Capital Expenditures,Working Capital Increase,Cash Flow,Discount Factor,Present Value Free Cash Flow
2022-12-31,261.960000,117.882000,-24.755220,-7.858800,-15.717600,139.100760,0.940000,130.754714
2023-12-31,309.112800,139.100760,-29.211160,-9.273384,-18.546768,164.138897,0.883600,145.033129
2024-12-31,364.753104,164.138897,-34.469168,-10.942593,-21.885186,193.683898,0.830584,160.870747
2025-12-31,430.408663,193.683898,-40.673619,-12.912260,-25.824520,228.547000,0.780749,178.437832
2026-12-31,507.882222,228.547000,-47.994870,-15.236467,-30.472933,269.685460,0.733904,197.923244
2027-12-31,599.301022,269.685460,-56.633947,-17.979031,-35.958061,318.228843,0.689870,219.536462
2028-12-31,707.175206,318.228843,-66.828057,-21.215256,-42.430512,375.510034,0.648478,243.509844
2029-12-31,834.466743,375.510034,-78.857107,-25.034002,-50.068005,443.101841,0.609569,270.101119
2030-12-31,984.670757,443.101841,-93.051387,-29.540123,-59.080245,522.860172,0.572995,299.596161
2031-12-31,1161.911493,522.860172,-109.800636,-34.857345,-69.714690,616.975003,0.538615,332.312062

In [32]:

msg = f"""Our projected Present Value of Projected Future Cash Flows are: {df['Present Value Free Cash Flow'].sum().round(2)}.
We are providing revenue guidance in 2032 to be: {round(df.iloc[-1]["Revenue"] * 1.18)}.
With an estimated EBITDA around: {round(df.iloc[-1]["Revenue"] * 1.18 * EBITDA_Margin)}.
The terminal value a this time given a multiple of {EBITDA_Exit_Multiple} and the above EBITDA for 2030, would equal: {round(df.loc["2031", "Revenue"][0] * 1.18 * EBITDA_Margin * EBITDA_Exit_Multiple)}
"""

print(msg)

Our projected Present Value of Projected Future Cash Flows are: 2178.08.
We are providing revenue guidance in 2032 to be: 1371.
With an estimated EBITDA around: 617.
The terminal value a this time given a multiple of 32.7 and the above EBITDA for 2030, would equal: 20175